function obj = save_to_db(obj, temperature, chi, N, convergence, C, T)
  if obj.SAVE_TO_DB
    sqlite3.execute('INSERT INTO tensors (temperature, chi, n, convergence, c, t) VALUES (?, ?, ?, ?, ?, ?)', ...
      temperature, chi, N, convergence, getByteStreamFromArray(C), getByteStreamFromArray(T));
    fprintf(['stored to database: \n' ...
      'temperature = ' num2str(temperature) ...
      ', chi = ' num2str(chi) ...
      ', N = ' num2str(N) ...
      ', convergence = ' num2str(convergence) '\n'])
  end
end
